"""empty message

Revision ID: 89ec9d388f0b
Revises: 56a730cd88ab
Create Date: 2019-03-10 13:24:33.882670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89ec9d388f0b'
down_revision = '56a730cd88ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('photo', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
